# This workflow will create a release when a version tag ist pushed
# For more information see: https://github.com/actions/create-release

name: Create GitHub Release

on:
  push:
    tags: "v*.*.*"

jobs:
  deploy:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
